###
# Crear un usuario
POST http://{{host}}/createUser
Content-Type: application/json

{
  "username": "usuario de prueba",
  "contrasena": "ejemplo123",
  "nombres": "nombre ejemplo",
  "apellidos": "apellidos ejemplo",
  "correo": "correo@gmail.com"
}

###
# Login
POST http://{{host}}/login
Content-Type: application/json

{
	"username": "usuario de prueba",
	"contrasena": "ejemplo123"
}

# SpecificArtist
POST http://{{host}}/SpecificArtist
Content-Type: application/json

{
	"nombre": "Sam Smith"
}

# songByGenre
POST http://{{host}}/songByArtist
Content-Type: application/json

{
	"genero": "pop"
}

# songByArtist
POST http://{{host}}/songByArtist
Content-Type: application/json

{
	"nombre": "Sam Smith"
}
# SpecificAlbum
POST http://{{host}}/specificAlbum
Content-Type: application/json
{
	"album": "Love Goes"
}

# SpecificSong
POST http://{{host}}/specificSong
Content-Type: application/json
{
	"nombre": "sauce"
}
# CreatPlayList
POST http://{{host}}/createPlaylist
Content-Type: application/json
{
	"nombre": "Nose"
}

###
# Obtener todos los artistas
GET http://{{host}}/artists
Accept: application/json

###
# Obtener todos los géneros
GET http://{{host}}/genres
Accept: application/json

###
# Obtener todos los álbumes
GET http://{{host}}/albums
Accept: application/json

###
# Obtener todas las canciones de la base de datos
GET http://{{host}}/songs
Accept: application/json

###
# Obtener todass las playlist
GET http://{{host}}/playlists
Accept: application/json

### =============================== REPORTES =================
# Los álbumes más recientes de la última semana
GET http://{{host}}/reports/weeklyAlbums
Accept: application/json

###
# Los artistas con popularidad creciente en los últimos tres meses
GET http://{{host}}/reports/growingArtists
Accept: application/json

###
# La cantidad de nuevas suscripciones mensuales en los últimos seis meses
GET http://{{host}}/reports/newSubscriptions
Accept: application/json

###
# Los artistas con mayor producción musical
GET http://{{host}}/reports/topArtist
Accept: application/json

###
# Los géneros más populares
GET http://{{host}}/reports/topGenres
Accept: application/json

###
# Usuarios más activos en la plataforma
GET http://{{host}}/reports/topActiveUsers
Accept: application/json
